### ISSUE TITLE
When out of bounds and a tile selected game crashes

### ISSUE THREAD

**Issue by catgirlchris** [Kyokofg99/rts_pygame#1]
Error que sucede a veces al salir de los bordes con un objeto para construir seleccionado.

```
Traceback (most recent call last):
  File "main.py", line 26, in <module>
    main()
  File "main.py", line 22, in main
    game.run()
  File "D:\Proyectos\rts_pygame\game\game.py", line 32, in run      
    self.update()
  File "D:\Proyectos\rts_pygame\game\game.py", line 48, in update   
    self.world.update(self.camera)
  File "D:\Proyectos\rts_pygame\game\world.py", line 42, in update  
    render_pos = self.world[grid_pos[0]][grid_pos[1]]["render_pos"] 
IndexError: list index out of range
PS D:\Proyectos\rts_pygame> 
```

**Comment by Kyokofg99** [comment]
still not solved keeps happening as soon as cursor leaves the tilemap

**Comment by Kyokofg99** [comment]
Now it should be completely solved. mouse_to_grid method needed to check what grid_pos was returning 74c9e142b00feb20c99e4ffbe5aa91b3684f720f
